### ISSUE TITLE
Funktioniert nicht unter rex 5.13.2

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/zip_install#15]
gibt die meldung es sei alles kopiert und ok – tatsächlich aber kein ordner angelegt.
gilt für .zip-upload sowie für link-installation von github.

**Comment by AWqxKAWERbXo** [comment]
Hier hatte ich ein ähnliches Problem - der Ordner wurde angelegt, blieb aber leer. Vermutlich fehlt(e) die ZIP-Extension.

**Comment by skerbis** [comment]
Die ZIP-Extension sollte serverseitig zur Verfügung stehen. Wenn dies nicht der Fall ist, sollte sich dieses AddOn eigentlich nicht installieren lassen. Hier gefixt: https://github.com/FriendsOfREDAXO/zip_install/commit/e251aa9010f04661426a4042c27aad1e111254df 
Danke @alxndr-w

**Comment by AWqxKAWERbXo** [comment]
Ich war mir nicht sicher, ob ich die Extension so richtig angegeben hatte. Wäre gut, wenn du das nochmal auf Plausibilität prüfen kannst @skerbis und @ansichtsache ob die Installation der aktuellen Version dann verweigert wird, wenn die zip-Extension fehlt.

Ich konnte es nirgends nachstellen.

**Comment by skerbis** [comment]
@alxndr-w hast alles richtig gemacht , zlib kann man aber rausnehmen 
<img width="1009" alt="Bildschirmfoto 2022-06-02 um 16 49 18" src="https://user-images.githubusercontent.com/791247/171657139-123ab061-70a7-4f89-ac50-a5e371050962.png">

**Comment by AWqxKAWERbXo** [comment]
Nur zu!

**Comment by skerbis** [comment]
Längst passiert 😀
