### ISSUE TITLE
accept=".zip" funktioniert in Chrome nicht

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/zip_install#4]
Es wird kein Fenster zum Datei wählen geöffnet. Entferne ich das Attribut, funktioniert alles.

**Comment by staabm** [comment]
gibts dazu nen chrome bug?

**Comment by IngoWinter** [comment]
Nicht dass ich wüsste. Ich kanns auch ausserhalb von Redaxo nicht reproduzieren, hier https://jsfiddle.net/winteringo/0adkqt0j/ funktioniert es. Testweises deaktivieren von JS im Backend brachte auch nix.

**Comment by hirbod** [comment]
Kann ich nicht bestätigen.
Chrome auf OSX mit Version 57.0.2987.133 (64-bit)

Läuft einwandfrei.

**Comment by IngoWinter** [comment]
Dann liegts wohl an irgendwas bei mir...
